export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="bira"
plugins=(zsh-fzf-history-search zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export PATH="$PATH:$HOME/.local/bin"
export EDITOR="vim"
