services:
  app:
    profiles:
      - full
    container_name: turbo-template-app-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./docker_data/api/logs:/app/apps/api/logs
      - ./docker_data/api/bucket:/app/apps/api/bucket
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    profiles:
      - full
      - db
    image: postgres:16
    container_name: turbo-template-db-dev
    volumes:
      - ./docker_data/psql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=turbo-template
      - TZ="Europe/Warsaw"
