- name: Setup web server
  hosts: home
  vars:
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
    user_name: runner
    app_name: turbo-template
  roles:
    - docker
    - user
    - shell
    - firewall
    - app
