# template file

server:
  http_listen_port: 9080
  grpc_listen_port: 9097

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "<URL>"

scrape_configs:
  - job_name: template-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: template-app
          __path__: ~/apps/turbo-template/data/logs/api/*.log
