# template file

global:
  scrape_interval: 120s

scrape_configs:
  - job_name: nestjs-service
    scrape_interval: 120s
    scrape_timeout: 30s
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - "prometheus:9090"
          - "app:3000"

remote_write:
  - url: <URL>
    basic_auth:
      username: <User name>
      password: <Your Grafana.com API Token>
