services:
  app:
    image: isur/turbo-template
    container_name: app
    env_file: ./.env.app
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: postgresql
    env_file: ./.env.db
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./configs/nginx-no-ssl:/etc/nginx
      - ./data/ssl/certbot:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
      - ./data/logs/nginx/:/var/log/nginx
    depends_on:
      - app
