services:
  app:
    image: isur/turbo-template
    container_name: app
    env_file: ./.env.app
    depends_on:
      - database
      - prometheus

  database:
    image: postgres:16
    container_name: postgresql
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env.db

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx-ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./data/ssl/certbot:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
      - ./data/logs/nginx/:/var/log/nginx
      - ./data/html:/var/www/html
    depends_on:
      - app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9095:9090"
    volumes:
      - ./configs/grafana/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - ./data/grafana-data:/var/lib/grafana
      - ./data/grafana_provisioning/provisioning:/etc/grafana/provisioning
    user: "0"
