name: Deploy Prod

on:
  push:
    branches:
      - master
    paths:
      - "apps/**"
      - "packages/**"
      - "configs/**"
      - "dockerfile"
  workflow_dispatch:

jobs:
  api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build docker
        run: docker build . -t isur/turbo-template

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key.key
          chmod 600 ~/.ssh/key.key
          cat >> ~/.ssh/config <<END
          HOST server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Upload docker
        run: docker save isur/turbo-template | ssh -C server docker load

      - name: Restart app
        run: |
          ssh server 'cd ~/apps/turbo-template; ./deploy.sh'
  front:
    name: Deploy FRONT
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 9.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Frontend
        run: pnpm build --filter=front

      - name: Upload front
        run: |
          rsync -avzr --delete ./apps/front/dist server:~/apps/turbo-template/data/html
